### ISSUE TITLE
Errors when using a non-valid Certificate

### ISSUE THREAD

**Issue by teddyking** [SpringerPE/firehose-to-syslog#1]
Hi there,

I'm trying to test the firehose-to-syslog out on a bosh-lite deployment of CF but it's failing because I'm using a self-signed cert.

I've implemented a quick fix for this locally by adding a `--skip-ssl-validation` flag and passing `&tls.Config{InsecureSkipVerify: skipSSLValidation}` through to noaa and gorequest. Would you be interested in a PR for this?

Cheers,
Ed

**Comment by simonjohansson** [comment]
Ah yeah, that would be great! :)

**Comment by simonjohansson** [comment]
PR solves the issue.
Thanks again.
